[[redirects]]
  from = "/source"
  to = "https://github.com/lorebooks-wiki/homepage"
  status = 301
  force = true

[[redirects]]
  from = "/issues"
  to = "/docs/issue-tracker"
  status = 301
  force = true

[build]
  publish = "site/"
  command = "./bin/netlify-build"

  # Exit early if the source files are unedited
  ignore = "git diff --quiet HEAD^ HEAD src/ mkdocs.yml netlify.toml bin/netlify-build"

# Post-processing stuff
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
