name: Project Homepage Builder
on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.x

jobs:
  publish-docs:
    name: Build documentation
    runs-on: ubuntu-20.04 # use latest LTS as possible
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python runtime
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          pip install -r requirements_gh-pages.txt
      - name: Build documentation
        run: |
          mkdocs build --config-file mkdocs_cicd.yml --verbose
